### ISSUE TITLE
Unexpected forcecloses in v0.1.41-alpha

### ISSUE THREAD

**Issue by Nordlenning** [CellularPrivacy/Android-IMSI-Catcher-Detector#831]
>Thank you for your feedback! Please add below details so that we can help you a bit faster.

---

#### Agreements
>Please check these boxes to ensure you've actually read and understood these important rules!

- [x] **I have reviewed and accepted the [guidelines for contributing](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md) to this project.**
- [x] **I have searched the [open Issues](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/issues) and made sure I am not filing a duplicate.**
- [x] **I have read the notes on [debugging](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md#debugging) and will properly maintain this Issue.**

---

#### Overview
>Please add a short and easy to understand description of the Issue you've experienced here.

There are 2 unexspected forcecloses that is discovered in 0.1.41 alfa (01.04.16 18:00)
Rooted Sony Experia lt25i CM Tsybasa (lollipop)

1. When you try to download OCID data in Aiplaine Mode W or WO wifi connected,
AIMSCID Crash.
Log of the inncident https://defuse.ca/b/PxOPvb8L1OeR9Q1aCRZpMD

2. When you are in map view & try to watch logging while you download OCID data, AIMSCID Crash.

Log of the inncident https://defuse.ca/b/NngQqTs5reAJo3pY3Elo7n

#### Reproduction
>Please tell us the detailed steps on how to reproduce your Issue here.

--- Same as above

#### References
>If your Issue is related to any other existing Issues or pull requests, please link them here.

---  Comments in 816 including screenshot
#### Screenshots
>If you experienced visual glitches, please add a screenshot without metadata here.

**Comment by Nordlenning** [comment]
Linked to wrong log in issue 1, this is correct >>  https://defuse.ca/b/Dzlf0aerUL87C1GIsdfBOx

**Comment by mimi89999** [comment]
I can reproduce 1., but not 2.

**Comment by Nordlenning** [comment]
To reproduce 2, -- with Wifi connected in Map View.
Push Download Button
Push Preferences 
Push Logging
AIMSCID Crash every time. See screenshot in 816

**Comment by mimi89999** [comment]
Ok. I can reproduce both.

**Comment by SecUpwN** [comment]
>Ok. I can reproduce both.

@mimi89999, if you'd be able to create fix, I'd instantly merge it!

**Comment by mimi89999** [comment]
I will do this ASAP...

**Comment by mimi89999** [comment]
#833

**Comment by mimi89999** [comment]
I didn't fix 2.

**Comment by Nordlenning** [comment]
Downloaded & test compiled latest 03.04.16 18:30 inkl merged fix for 833. Latest commit to source 833.
Result: Request API Key = Crash. Download Data in Airplain Mode = Crash 
Will test New APK release Later tonight.

**Comment by mimi89999** [comment]
On my device: Request API Key = Fixed; Download Data in Airplain Mode = Fixed.

**Comment by SecUpwN** [comment]
>I didn't fix 2.

Strange. How come I can't replicate the second Issue then? Feel free to re-open should it still exist.

**Comment by mimi89999** [comment]
@SecUpwN I don't have the required permissions to reopen issues that you closed.

**Comment by SecUpwN** [comment]
>I don't have the required permissions to reopen issues that you closed.

Congratulaitions, you are now an official `COLLABORATOR`. Get a profile picture, dude. :)

**Comment by mimi89999** [comment]
@Nordlenning Could you please give me the log?

**Comment by Nordlenning** [comment]
Downloaded & test compiled latest 03.04.16 19:30
Result: Request API Key = WORKS. Download Data in Airplain Mode = WORKS
Thank you @mimi89999, I Download latest source from github with smartgit & compile w AStudio in Linux Kali Sana Distro.

**Comment by Nordlenning** [comment]
@mimi89999 Issue 2 also Works on my sony now. I cant reproduce it any more, great job..5 star

**Comment by mimi89999** [comment]
That's strange. I haven't done anything to fix it, but I also couldn't reproduce it recently...

**Comment by mimi89999** [comment]
@SecUpwN To reproduce 2.:
1. The device can't be in airplane mode
2. Go to map view
3. Click download button
4. Click the 3 dots
5. Click on debuging or settings (it doesn't matter)
Repeat 2-5 untill... the app will crash :-)

**Comment by SecUpwN** [comment]
>Repeat 2-5 untill... the app will crash :-)

I don't get it. Is this fixed now or not? :P

**Comment by mimi89999** [comment]
No, it's not fixed, but it's hard to reproduce. Please follow my instructions.

**Comment by mimi89999** [comment]
You reopened this issue... Does that mean that you can reproduce 2.?

**Comment by mimi89999** [comment]
@Nordlenning Could you try again to reproduce 2.?

**Comment by SecUpwN** [comment]
>You reopened this issue... Does that mean that you can reproduce 2.

I tried to, but for me it seems to work flawlessly. Reopened because I thought you still experience it?

**Comment by mimi89999** [comment]
I will add more logging to investigate this issue.

**Comment by Nordlenning** [comment]
Now I have tried 20-30 times, can not reproduce this any more following youre steps  @mimi89999 
But i managed to freeze AIMSCID 5 times when I pushed Map View. Total shutdown. BEFORE I even got to the menu. No problems pushing  Download - preferences or debugging. Downloaded OK  Logged OK.

**Comment by SecUpwN** [comment]
>But i managed to freeze AIMSCID 5 times when I pushed Map View. Total shutdown.

Please anonymize the logfiles and share them with us here using [PIEBIN](https://defuse.ca/pastebin.htm). Thanks.

**Comment by Nordlenning** [comment]
I managed to freeze it again, I will hook my phone up with my lap & get logcat of this, but it is not easy to reproduce, you have to repeat many times to get it to freeze..

**Comment by mimi89999** [comment]
I agree.

**Comment by SecUpwN** [comment]
>but it is not easy to reproduce, you have to repeat many times to get it to freeze..

@mimi89999, since you also requested access to [our Coverity Scan](https://scan.coverity.com/projects/3346), can you see if this was catched?

**Comment by Nordlenning** [comment]
I got it, @mimi89999 Maybe this rather long logcat will help.
https://defuse.ca/b/4Inwhe4XhXfcqj7kKWuz4Q
 04-03 22:02:07.579: D/AndroidRuntime(4409): --------- beginning of crash
 04-03 22:02:07.579: E/AndroidRuntime(4409): FATAL EXCEPTION: main
 04-03 22:02:07.579: E/AndroidRuntime(4409): Process: com.SecUpwN.AIMSICD, PID: 4409

**Comment by Nordlenning** [comment]
Did not mean to close, double click, sorry7

**Comment by mimi89999** [comment]
How much RAM do you have on your device?

**Comment by Nordlenning** [comment]
1GB

**Comment by Nordlenning** [comment]
I can also reproduce it in WIP TEST RELEASE v0.1.42-alpha, but you have to work for it, same log result. 
![screenshot from 2016-04-04 00 48 14](https://cloud.githubusercontent.com/assets/17292772/14235475/ff11ea8e-f9ee-11e5-8c2b-92392c6e5c60.png)

**Comment by mimi89999** [comment]
@Nordlenning Please apply https://github.com/mimi89999/Android-IMSI-Catcher-Detector/commit/77602319d54c95c486a5ff86d2fff1e9515b4a1b , build the app and test it again.

**Comment by Nordlenning** [comment]
Just committed your changes to RequestTask.java @mimi89999 & will build new app & test it out,

**Comment by mimi89999** [comment]
@Nordlenning How does the app work now?

**Comment by Nordlenning** [comment]
So fa so good, cant crash it & I'm working hard on it !

**Comment by Nordlenning** [comment]
So I have tested: Inserting OCID key OK, Download OCID Key OK, Download OCID Data both from menu & map view OK. Download OCID data in Aiplaine Mode W or WO wifi connected OK, upload OCID Data OK. Can not reproduce issue 2. Only tiny thing i noticed was that Notification Icon stops spinning when you pull menu out (from left). But that's not the issue. Looks like its all solved.

**Comment by Nordlenning** [comment]
Log https://defuse.ca/b/USoUPmAujCvFP3qwWruF0b

![screenshot from 2016-04-22 16 40 12](https://cloud.githubusercontent.com/assets/17292772/14745193/beea9762-0899-11e6-8c67-5539b9b9bf33.png)

**Comment by SecUpwN** [comment]
@Nordlenning, so you keep experiencing this Issue? Which version do you use?

**Comment by Nordlenning** [comment]
As stated above, WIP TEST RELEASE v0.1.42-alpha compiled 19 days ago. I have plenty more screenshots & logs.. See more logs & pics in issue 852...

**Comment by agilob** [comment]
Please re-open.

**Comment by SecUpwN** [comment]
>Please re-open.

@agilob, why? If you still experience this Issue, please attach logs from the the current `v0.1.43-alpha`.

**Comment by Nordlenning** [comment]
WIP TEST RELEASE v0.1.43-alpha Crash when Downloading OCID data in Map View. 
Crash when Downloading OCID data without WiFi from menu & more crash in 870

I don't have the required permissions to reopen issues

**Comment by SecUpwN** [comment]
@mimi89999, would you please check this again?

**Comment by mimi89999** [comment]
I will look at it...

**Comment by mimi89999** [comment]
I can't download OCID data, but the latest version built from source isn't crashing on my device.

**Comment by Nordlenning** [comment]
I em Closing this in favor of 870. No use in keeping both open.
